import { useState } from 'react';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100 text-gray-900">
      <header className="bg-blue-600 text-white py-4">
        <div className="container mx-auto flex justify-between items-center px-4">
          <h1 className="text-xl font-bold">Dr. med. Martin Jütz</h1>
          <nav>
            <ul className="flex space-x-4">
              <li><Link href="/">Home</Link></li>
              <li><Link href="/about">Über uns</Link></li>
              <li><Link href="/services">Leistungen</Link></li>
              <li><Link href="/contact">Kontakt</Link></li>
              <li><Link href="/impressum">Impressum</Link></li>
            </ul>
          </nav>
        </div>
      </header>

      <main className="container mx-auto py-12 px-4">
        <h2 className="text-3xl font-semibold mb-6">Willkommen in unserer Praxis</h2>
        <p className="text-lg">Ihre Gesundheit ist unsere Priorität. Nutzen Sie unsere telemedizinischen Angebote für eine schnelle und sichere Beratung.</p>
        <div className="mt-6">
          <Link href="/contact" className="px-6 py-2 bg-blue-600 text-white rounded-lg">Online-Sprechstunde buchen</Link>
        </div>
      </main>

      <footer className="bg-gray-800 text-white py-4 mt-12 text-center">
        <p>&copy; {new Date().getFullYear()} Dr. med. Martin Jütz – Alle Rechte vorbehalten.</p>
      </footer>
    </div>
  );
}

// Neue Seite: Leistungen
export function Services() {
  return (
    <div className="min-h-screen bg-gray-100 text-gray-900">
      <header className="bg-blue-600 text-white py-4">
        <div className="container mx-auto flex justify-between items-center px-4">
          <h1 className="text-xl font-bold">Unsere Telemedizinischen Leistungen</h1>
          <nav>
            <ul className="flex space-x-4">
              <li><Link href="/">Home</Link></li>
              <li><Link href="/about">Über uns</Link></li>
              <li><Link href="/contact">Kontakt</Link></li>
              <li><Link href="/impressum">Impressum</Link></li>
            </ul>
          </nav>
        </div>
      </header>

      <main className="container mx-auto py-12 px-4">
        <h2 className="text-3xl font-semibold mb-6">Unsere telemedizinischen Angebote</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Online-Sprechstunde per Videochat</li>
          <li>Digitale Rezepte und Krankschreibungen</li>
          <li>Telemedizinische Beratung für akute Beschwerden</li>
          <li>Chronische Krankheitsbetreuung per Fernüberwachung</li>
          <li>Digitale Übermittlung und Auswertung von Laborergebnissen</li>
          <li>Beratung zu Prävention und Gesundheitsförderung online</li>
        </ul>
      </main>

      <footer className="bg-gray-800 text-white py-4 mt-12 text-center">
        <p>&copy; {new Date().getFullYear()} Dr. med. Martin Jütz – Alle Rechte vorbehalten.</p>
      </footer>
    </div>
  );
}
